---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-log4j-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    instance: {{ $.Chart.Name }}
  annotations:
    doc: {{ $.Values.docURL }}
data:
  ksql-log4j.properties: |
    log4j.rootLogger=INFO, stdout

    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=net.logstash.log4j.JSONEventLayoutV1

    log4j.logger.kafka=ERROR, stdout
    log4j.logger.org.apache.kafka.streams=INFO, streams
    log4j.additivity.org.apache.kafka.streams=false
    log4j.logger.org.apache.zookeeper=ERROR, stdout
    log4j.logger.org.apache.kafka=ERROR, stdout
    log4j.logger.org.I0Itec.zkclient=ERROR, stdout
